#define 정수 int
#define 부동 float
#define 따블 double
#define 허수 i
#define 열고 {
#define 닫고 }
#define 메인 main
#define 괄호열고 (
#define 괄호닫고 )
#define 앙 ;
#define 은 =
#define 는 =
#define 더하기 +
#define 빼기 -
#define 곱하기 *
#define 나누기 /
#define 더한다 +=
#define 뺸다 -=
#define 하나더하기 ++
#define 하나빼기 --
#define 형식출력 printf
#define 출력 puts
#define 형식입력 scanf
#define 입력 gets
#define 만약 if
#define 구간반복 for
#define 반복 while
#define 포인터 &
#define 가보다작다 <
#define 가보다크다 >
#define 가보다작거나같다 <=
#define 가보다크거나같다 >=
#define 같아 ==
#define 같지않아 !=
#define 리턴제로부터시작하는이세계생활 return 0;